nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
sexo = input("Digite seu sexo: ")
endereco = input("Digite seu endereço: ")
telefone = input("Digite seu telefone: ")

print("Nome:", nome)
print("Idade:", idade)
print("Sexo:", sexo)
print("Endereco:", endereco)
print("Telefone:", telefone)
